name: Windows Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Cleanup
        run: flutter clean
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
          cache: true
      - name: Get dependencies
        run: flutter pub get

      - name: Start release build
        run: flutter build windows --release

      - uses: actions/upload-artifact@v4
        with:
          name: release-0.2.1
          path: build\windows\x64\runner\Release

      - name: Create MSIX package 
        run: flutter pub run msix:create

      - uses: actions/upload-artifact@v4
        with:
          name: release-windows
          path: build\windows\x64\runner\Release\donpmm.msix
